# Generated by Django 4.1.7 on 2023-05-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0004_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GNSSData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=8)),
                ('coordinate', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=15)),
                ('satellitesCount', models.CharField(max_length=2)),
                ('dataFlag', models.CharField(max_length=15)),
            ],
        ),
    ]
