# Generated by Django 4.1.7 on 2023-05-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_driverstatus_gnssdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DriverStatus',
        ),
        migrations.DeleteModel(
            name='GNSSData',
        ),
    ]
