# Generated by Django 4.1.7 on 2023-05-22 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0006_delete_driverstatus_delete_gnssdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
