# Generated by Django 4.1.7 on 2023-05-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0007_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('name', models.TextField()),
                ('cost', models.TextField()),
                ('color', models.CharField(max_length=20)),
                ('composition', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=20)),
            ],
        ),
    ]
