# Generated by Django 4.1.7 on 2023-05-23 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0009_item_for_men'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Item_for_men',
            new_name='Men_item',
        ),
    ]
