# Generated by Django 4.1.7 on 2023-05-24 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0010_rename_item_for_men_men_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cost',
        ),
    ]
