# Generated by Django 4.1.7 on 2023-05-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0011_remove_item_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Men_item',
        ),
    ]
