# Generated by Django 4.1.7 on 2023-05-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0012_delete_item_delete_men_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.TextField()),
                ('count_this_item', models.IntegerField()),
                ('name', models.TextField()),
                ('cost', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('composition', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('size', models.CharField(max_length=20)),
            ],
        ),
    ]
