# Generated by Django 4.1.7 on 2023-05-24 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0013_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id_item',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
