# Generated by Django 4.1.7 on 2023-05-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0014_item_id_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='id_popup',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
